// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"github.com/speakeasy-sdks/us-test-nolan/v3/pkg/models/shared"
)

// HTTPValidationError - Validation Error
type HTTPValidationError struct {
	Detail []shared.ValidationError `json:"detail,omitempty"`
}

var _ error = &HTTPValidationError{}

func (e *HTTPValidationError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
