// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
)

type HTTPValidationError struct {
	Detail []ValidationError `json:"detail,omitempty"`
}

var _ error = &HTTPValidationError{}

func (e *HTTPValidationError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
