// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ValidationError struct {
	Loc  []interface{} `json:"loc"`
	Msg  string        `json:"msg"`
	Type string        `json:"type"`
}

func (o *ValidationError) GetLoc() []interface{} {
	if o == nil {
		return []interface{}{}
	}
	return o.Loc
}

func (o *ValidationError) GetMsg() string {
	if o == nil {
		return ""
	}
	return o.Msg
}

func (o *ValidationError) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}
